server:
  servlet:
    context-path: /spring-test
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sys
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
